export const ActionTypes = {
    SET_CAT_LIST: "SET_CAT_LIST",
    SET_SUBCAT_LIST: "SET_SUBCAT_LIST",
    GET_SUBCAT_LIST: "GET_SUBCAT_LIST",
    GET_CAT_LIST: "GET_CAT_LIST",
    SET_CAT_LIST_ERROR: "SET_CAT_LIST_ERROR",

    SET_PRODUCT_LIST: "SET_PRODUCT_LIST",
    GET_PRODUCT_LIST: "GET_PRODUCT_LIST",
    SET_PRODUCT_LIST_ERROR: "SET_PRODUCT_LIST_ERROR",
    SET_USER_NAME: "SET_USER_NAME",
    SET_USER_DATA: "SET_USER_DATA",
    GET_USER_LOGIN: "GET_USER_LOGIN",
    ERR_USER_LOGIN: "ERR_USER_LOGIN",
    USER_NAME_D: "USER_NAME_D",
  };